version: "3.2"
services:
  angular:
    build: './safe/'
    container_name: angular
    ports:
      - "4200:4200"
    depends_on:
      - nodejs
    networks:
      - frontend
      - backend
  nodejs:
    build: './safeBack/'
    container_name: nodejs
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend:
